name: Build PxCrypt - Windows
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
env:
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  pxcrypt_src_suffix: PxCrypt/Source
  pxcrypt_src_dir: ${{ github.workspace }}/PxCrypt/Source
  pxcrypt_build_dir: ${{ github.workspace }}/PxCrypt/Build

jobs:
  build-pxcrypt:
    name: Build PxCrypt - Windows (Release)
    strategy:
      fail-fast: false
      matrix:
        lib_linkage: [shared, static]
        include:
          - lib_linkage: shared
            cmake_bsl: ON
          - lib_linkage: static
            cmake_bsl: OFF
    runs-on: windows-latest
    env:
      vs_dir: C:/Program Files/Microsoft Visual Studio/2022/Enterprise
      cmake_gen: Ninja Multi-Config
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |
        echo "pxcrypt_package_path=${{ env.pxcrypt_build_dir }}/out/dist" >> $Env:GITHUB_ENV
        $pxcrypt_install_path="${{ env.pxcrypt_build_dir }}/out/install"
        echo "pxcrypt_install_path=$pxcrypt_install_path" >> $Env:GITHUB_ENV
        echo "qt_cmake=${Env:qt_install_dir}/bin/qt-cmake.bat" >> $Env:GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.5.1
        os: windows
        compiler: msvc2022
        linkage: ${{ matrix.lib_linkage }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Install Doxygen
      uses: oblivioncth/actions/general/cache-and-install-doxygen-from-ffynnon@dev
      with:
        version: 1.9.7
        os: windows
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Install Graphviz
      run: choco install graphviz  
    - name: Checkout PxCrypt
      uses: actions/checkout@v3
      with:
        path: ${{ env.pxcrypt_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly  
    - name: Build/Install PxCrypt
      working-directory: ${{ env.pxcrypt_src_dir }}
      shell: cmd
      run: |
        echo "Setup C++ Build Environment..."
        CALL "${{ env.vs_dir }}\Common7\Tools\VsDevCmd.bat" -arch=amd64
        echo "Configure CMake using Qt wrapper..."
        CALL "${{ env.qt_cmake }}" -G "${{ env.cmake_gen }}" -S "${{ env.pxcrypt_src_dir}}" -B "${{ env.pxcrypt_build_dir }}" -D BUILD_SHARED_LIBS=${{ matrix.cmake_bsl }} -D PXCRYPT_TESTS=ON -D PXCRYPT_DOCS=ON
        echo "Changing to build directory..."
        cd "%pxcrypt_build_dir%"
        echo "Building PxCrypt Release/Docs..."
        cmake --build . --target all --config Release
        echo "Running tests..."
        ctest -C Release --output-on-failure
        echo "Installing PxCrypt Release/Docs..."
        cmake --install . --config Release
        echo "Packaging PxCrypt..."
        cpack -C "Release"
        echo "Build complete."
    - name: Get PxCrypt artifact name
      run: |
        $artifact_name=$((Get-ChildItem -Path "${{ env.pxcrypt_package_path }}" -Filter *.zip)[0].BaseName)
        echo "current_artifact_name=$artifact_name" >> $Env:GITHUB_ENV
    - name: Upload PxCrypt build artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.current_artifact_name }}
        path: ${{ env.pxcrypt_install_path }}
        if-no-files-found: error
