name: Build PxCrypt - Linux
on:
  workflow_call:
    secrets:
      qt_ffynnon_cred:
        description: 'Credentials for getting Qt from Ffynnon'
        required: true
    outputs:
      doc_artifact_name:
        description: "Name of artifact used to update docs"
        value: ${{ jobs.build-pxcrypt.outputs.doc_artifact_name }}
env:
  qt_install_dir: ${{ github.workspace }}/Qt/Install
  pxcrypt_src_suffix: PxCrypt/Source
  pxcrypt_src_dir: ${{ github.workspace }}/PxCrypt/Source
  pxcrypt_build_dir: ${{ github.workspace }}/PxCrypt/Build

jobs:
  build-pxcrypt:
    name: Build PxCrypt - Linux (Release)
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04]
        compiler: [{c: gcc-10, cxx: g++-10, qt: clang12}, {c: gcc-12, cxx: g++-12, qt: clang14}, {c: clang-12, cxx: clang++-12, qt: clang12}, {c: clang-14, cxx: clang++-14, qt: clang14}]
        linkage: [{type: shared, cmake_bsl: ON}, {type: static, cmake_bsl: OFF}]
        exclude:
            - os: ubuntu-20.04
              compiler: {c: gcc-12, cxx: g++-12, qt: clang14}
            - os: ubuntu-20.04
              compiler: {c: clang-14, cxx: clang++-14, qt: clang14}
            - os: ubuntu-22.04
              compiler: {c: gcc-10, cxx: g++-10, qt: clang12}
            - os: ubuntu-22.04
              compiler: {c: clang-12, cxx: clang++-12, qt: clang12}
    runs-on: ${{ matrix.os }}
    env:
      cmake_gen: Ninja Multi-Config
    outputs:
      doc_artifact_name: ${{ steps.set_doc_artifact_name.outputs.doc_artifact_name }}
    steps:
    - name: Set derived variables with shell because GitHub Actions env context sucks
      run: |  
        echo "pxcrypt_package_path=${{ env.pxcrypt_build_dir }}/out/dist" >> $GITHUB_ENV
        pxcrypt_install_path="${{ env.pxcrypt_build_dir }}/out/install"
        echo "pxcrypt_install_path=$pxcrypt_install_path" >> $GITHUB_ENV
        echo "qt_cmake=$qt_install_dir/bin/qt-cmake" >> $GITHUB_ENV
    - name: Install Qt (custom build)
      uses: oblivioncth/actions/general/install-and-cache-qt-from-ffynnon@dev
      with:
        version: 6.5.1
        os: linux
        compiler: ${{ matrix.compiler.qt }}
        linkage: ${{ matrix.linkage.type }}
        path: ${{ env.qt_install_dir }}
        credentials: ${{ secrets.qt_ffynnon_cred }}
    - name: Install Doxygen
      uses: oblivioncth/actions/ubuntu/install-doxygen-from-sourceforge@dev
      with:
        version: 1.9.8
    - name: Install Graphviz
      run: sudo apt-get install graphviz
    - name: Install Ninja
      run: sudo apt-get install ninja-build
    - name: Install Harfbuzz
      run: sudo apt-get install libharfbuzz-dev
    - name: Install XCB Related libs
      run: sudo apt-get install libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev libxcb-*-dev
    - name: Install libdrm
      run: sudo apt-get install libdrm-dev
    - name: Install OpenGL lib
      run: sudo apt-get install libglu1-mesa-dev
    - name: Install EGL [22.04]
      if: matrix.os == 'ubuntu-22.04'
      run: sudo apt-get install libegl1-mesa-dev
    - name: Checkout PxCrypt
      uses: actions/checkout@v4
      with:
        path: ${{ env.pxcrypt_src_suffix }}
        fetch-depth: 0 # Required for verbose versioning to work correctly
    - name: Build/Install PxCrypt
      working-directory: ${{ env.pxcrypt_src_dir }}
      run: |
        echo Configuring CMake...
        "$qt_cmake" -G "$cmake_gen" -S "$pxcrypt_src_dir" -B "$pxcrypt_build_dir" -D CMAKE_CXX_COMPILER="${{ matrix.compiler.cxx }}" -D CMAKE_C_COMPILER="${{ matrix.compiler.c }}" -D BUILD_SHARED_LIBS="${{ matrix.linkage.cmake_bsl }}" -D PXCRYPT_TESTS=ON -D PXCRYPT_DOCS=ON
        echo Changing to build directory...
        cd "$pxcrypt_build_dir"
        echo Building PxCrypt Release/Docs...
        cmake --build . --target all --config Release
        echo Running tests...
        ctest -C Release --output-on-failure
        echo Installing PxCrypt Release/Docs
        cmake --install . --config Release
        echo Packaging PxCrypt...
        cpack -C "Release"
        echo Build complete.
    - name: Get PxCrypt artifact name
      id: get_artifact_name
      run: |
        cpack_name=$(find "${{ env.pxcrypt_package_path }}" -type f -name "*.zip")
        artifact_name="$(basename "$cpack_name" .zip) [${{ matrix.compiler.cxx }}]"
        echo "current_artifact_name=$artifact_name" >> $GITHUB_ENV
    - name: Set doc artifact name
      id: set_doc_artifact_name
      if: matrix.linkage.type == 'static' && matrix.compiler.cxx == 'clang++-14' 
      run: echo "doc_artifact_name=${{ env.current_artifact_name }}" >> $GITHUB_OUTPUT
    - name: Upload PxCrypt build artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.current_artifact_name }}
        path: ${{ env.pxcrypt_install_path }}
        if-no-files-found: error
