name: PxCrypt Push Reaction
on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'main'

jobs:
  trigger-windows-build:
    name: Build PxCrypt (Windows)
    uses: ./.github/workflows/build-pxcrypt-windows.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}
      
  trigger-linux-build:
    name: Build PxCrypt (Linux)
    uses: ./.github/workflows/build-pxcrypt-linux.yml
    secrets:
      qt_ffynnon_cred: ${{ secrets.OBYBOT_FFYNNON_CREDS }}